---
title       : BMI and BMR calculators
subtitle    : Coursera project
author      : Przemek
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---


<style>
strong {
  font-weight: bold;
}
</style>


## About application
Application contains BMI and BMR calculators that allows you to check your Body Mass Index and Basal metabolic rate.

One can access an application using link:
https://przemekd.shinyapps.io/DDP_shinyApp/

---

## BMR and BMI Definition

**Basal metabolic rate (BMR)**, and the closely related resting metabolic rate (RMR), is the rate of energy expenditure by humans and other animals at rest, and is measured in kJ per hour per kg body mass.

**The body mass index (BMI)**, or Quetelet index, is a measure of relative weight based on an individual's mass and height.

--- .class #id

## BMI and BMR equations
There are two equation that are used to calculate outputs in this shinyApp.
Equation for calculating body mass index:

$$BMI = (\frac{mass}{height*height})\frac{kg}{m*m}$$

The Mifflin St Jeor Equation for calculating basal metabolic rate:

$$BMR = (\frac{10.0 m}{1 kg} + \frac{6.25 h}{1 cm} - \frac{5.0 a}{1 year} + s)\frac{kcal}{day}$$, where s is +5 for men and -161 for women

---

## BMI Plot
In the application a plot is use to visualize BMI category. This plot is recreated in this slide by using R code (not all code shown here).
```{r, echo=c(9), fig.height=3, fig.align = 'center', message = F}
library(ggplot2)
wt = seq(30,220, length.out=1000)
ht1 = sqrt(wt/18.5)*100
ht2 = sqrt(wt/24.9)*100
ht3 = sqrt(wt/30.0)*100
htmin= rep(0,1000)
htmax= rep(220,1000)

ww <- data.frame(x = c(wt,wt,wt,wt),
                 ymin = c(ht1,ht2,ht3,htmin),
                 ymax = c(htmax,ht1,ht2,ht3),
                 grp = rep(c('Underweight','Normal', 'Overweight', 'Obesity'),
                           each = 1000))
ggplot(data = ww,aes(x = x,ymin = ymin, ymax = ymax,fill = grp)) + #rest of code hidden 
  geom_ribbon(alpha = 1) +
  scale_fill_manual(name = "BMI Category"
                    ,values = c('Underweight' = 'lightblue',
                                'Normal' = 'green', 
                                'Overweight' = 'yellow', 
                                'Obesity' = 'red')
                    ,breaks = c('Underweight','Normal','Overweight','Obesity')
                    )+
  coord_cartesian(xlim = c(40, 210), ylim = c(120, 220))+
  scale_x_continuous("Weight [kg]", breaks = seq(10, 220, 20)) +
  scale_y_continuous("Height [cm]", breaks = seq(120, 220, 20))+
  theme_bw() +
  geom_vline(xintercept=seq(50, 200, by=10), alpha=0.7, colour="white", linetype="longdash") +
  geom_hline(yintercept=seq(130, 210, by=10), alpha=0.7, colour="white", linetype="longdash")
```









